## CHANGE this to the name of your plugin.
name: FasterToolsAddon

## CHANGE this to your username.
author: Sami2EaCOS

## CHANGE this to a meaninful but short description of your plugin.
description: FasterTools is a Slimefun4 Addon created to improved harvest speed.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.smourad.fastertools.FasterToolsAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Sami2EaCOS/FasterTools

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19

## This is required and marks Slimefun as a plugin dependency.
depend:
- ProtocolLib
- Slimefun